# Dataset documentation ------------------------------------------------------

#' Simulated lexical-decision experiment
#'
#' A reproducibly simulated psycholinguistic lexical-decision experiment, in
#' which participants judge whether letter strings are real words. The design
#' is fully crossed and counterbalanced: 24 participants each respond to all 40
#' items once (960 trials). `condition` (related/unrelated priming) and
#' `modality` (visual/auditory) are both within-participant and within-item,
#' assigned by a Latin-square list rotation so that, across participants, every
#' item appears equally often in each condition and in each modality. Neither
#' factor is therefore collinear with the item random intercept, which makes
#' this a clean fit for crossed-random-effects models such as
#' `lmer(RT ~ condition + modality + word_frequency + (1 | participant) +
#' (1 | item))`, and hence for [optimizer_fixef_plot()], [coefficient_plot()]
#' and the distribution plots.
#'
#' `RT` is generated log-normally from participant and item random intercepts
#' plus the fixed effects (unrelated priming about 35 ms slower; auditory a
#' touch slower; more frequent words faster), with a 250 ms floor; RT analyses
#' should use correct trials (`accuracy == 1`). `accuracy` is generated from
#' the exogenous predictors (`word_frequency`, `condition`, `modality`) and
#' random effects only - it is not derived from `RT` - so classification demos
#' built on it are not circular.
#'
#' The data are synthetic, generated by `data-raw/generate_datasets.R` with a
#' fixed seed; they do not describe any real individuals.
#'
#' @format A data frame with 960 rows and 7 variables:
#' \describe{
#'   \item{participant}{Participant identifier (factor, 24 levels).}
#'   \item{item}{Item identifier (factor, 40 levels).}
#'   \item{condition}{Priming condition (factor): `related` or `unrelated`.}
#'   \item{modality}{Presentation modality (factor): `visual` or `auditory`.}
#'   \item{word_frequency}{Item-level word frequency on the Zipf scale.}
#'   \item{RT}{Reaction time, in milliseconds.}
#'   \item{accuracy}{Response accuracy: 1 correct, 0 incorrect.}
#' }
#' @source Simulated; see `data-raw/generate_datasets.R`.
"lexical_decision"

#' Simulated wellbeing survey
#'
#' A reproducibly simulated cross-sectional wellbeing survey for descriptive,
#' correlation, regression and missing-data examples. `life_satisfaction`
#' responds meaningfully to its predictors: higher stress lowers it, more sleep
#' and exercise raise it, log-income has a real positive effect (about +0.4 per
#' natural-log unit), and age has a mild inverted-U (peaking in mid-life).
#' `education` is an ordered factor. Income is missing more often at higher
#' stress (missing at random); because income genuinely predicts the
#' outcome, this missingness is informative for the missing-data examples.
#'
#' The data are synthetic, generated by `data-raw/generate_datasets.R` with a
#' fixed seed; they do not describe any real individuals.
#'
#' @format A data frame with 300 rows and 9 variables:
#' \describe{
#'   \item{id}{Respondent identifier.}
#'   \item{region}{Region of residence: `North`, `South`, `East` or `West`.}
#'   \item{age}{Age in years.}
#'   \item{education}{Highest education level (ordered factor:
#'     `secondary` < `undergraduate` < `postgraduate`).}
#'   \item{income}{Annual income; contains missing values (more at high stress).}
#'   \item{stress}{Self-reported stress (1-7).}
#'   \item{sleep_hours}{Typical hours of sleep per night; contains missing values.}
#'   \item{exercise_days}{Days of exercise per week (0-7); contains missing values.}
#'   \item{life_satisfaction}{Life satisfaction (1-7); contains missing values.}
#' }
#' @source Simulated; see `data-raw/generate_datasets.R`.
"wellbeing_survey"

#' Simulated crop-yield field trial
#'
#' A reproducibly simulated agronomy field trial relating crop yield to
#' rainfall, fertiliser, soil pH and a management treatment. Used for the
#' regression, coefficient-plot, scatter-trend and interaction examples. The
#' data-generating process contains a genuine fertiliser-by-treatment
#' interaction: fertiliser raises yield far more under the `enhanced` treatment
#' than under `standard`, so `interaction_plot(lm(yield ~ fertiliser *
#' treatment + ..., crop_yield), "fertiliser", "treatment")` shows real,
#' diverging slopes rather than noise. The main effects (rainfall, fertiliser,
#' soil pH and treatment) are retained.
#'
#' The data are synthetic, generated by `data-raw/generate_datasets.R` with a
#' fixed seed.
#'
#' @format A data frame with 200 rows and 6 variables:
#' \describe{
#'   \item{field}{Field identifier.}
#'   \item{treatment}{Management treatment (factor): `standard` or `enhanced`.}
#'   \item{rainfall}{Seasonal rainfall, in millimetres.}
#'   \item{fertiliser}{Fertiliser applied, in kilograms per hectare.}
#'   \item{soil_ph}{Soil pH.}
#'   \item{yield}{Crop yield, in tonnes per hectare.}
#' }
#' @source Simulated; see `data-raw/generate_datasets.R`.
"crop_yield"

#' Simulated two-arm clinical trial
#'
#' A reproducibly simulated randomised clinical trial, for time-to-event
#' (survival) and imbalanced-classification examples. The two arms have a real
#' survival difference: the `treatment` arm has a lower hazard, so the
#' Kaplan-Meier curves separate clearly and the log-rank test is highly
#' significant, and - because its event times are longer - the treatment arm is
#' more often right-censored by the 36-month study end. `age` and `biomarker`
#' also affect the hazard. The data feed [survival_plot()] (pass `time`,
#' `event` and `arm`, or a `survival::survfit` object).
#'
#' `adverse_event` is a deliberately rare binary safety outcome (about a 10%
#' base rate) that is predictable from `arm`, `age` and `biomarker`. It gives
#' the precision-recall ([pr_curve_plot()]), cumulative-gains ([gain_plot()]),
#' lift ([lift_plot()]) and calibration ([calibration_plot()]) demos a
#' genuinely imbalanced target, where those charts are most informative.
#'
#' The data are synthetic, generated by `data-raw/generate_datasets.R` with a
#' fixed seed; they do not describe any real individuals.
#'
#' @format A data frame with 300 rows and 7 variables:
#' \describe{
#'   \item{patient}{Patient identifier.}
#'   \item{arm}{Treatment arm (factor): `placebo` or `treatment`.}
#'   \item{age}{Age in years at enrolment.}
#'   \item{biomarker}{Standardised baseline laboratory value.}
#'   \item{time}{Follow-up time, in months.}
#'   \item{event}{Event indicator: 1 event observed, 0 right-censored.}
#'   \item{adverse_event}{Rare adverse-event indicator: 1 yes, 0 no
#'     (about 10% positive).}
#' }
#' @source Simulated; see `data-raw/generate_datasets.R`.
"clinical_trial"

#' Simulated monthly sales time series
#'
#' A reproducibly simulated seasonal monthly time series in tidy long form, for
#' the time-series examples. It holds two product lines (`indoor` and
#' `outdoor`), each with six years of monthly observations carrying a linear
#' trend, a clear twelve-month seasonal cycle (with different seasonal peaks per
#' line) and noise. The two-series shape exercises the multi-group
#' [timeseries_plot()] path on first-party data; extracting one series as a
#' monthly `ts` (frequency 12) lets [decompose_plot()] and [acf_plot()] reveal
#' the trend and seasonality.
#'
#' The data are synthetic, generated by `data-raw/generate_datasets.R` with a
#' fixed seed.
#'
#' @format A data frame with 144 rows and 3 variables:
#' \describe{
#'   \item{date}{First day of the month (`Date`), from January 2018.}
#'   \item{series}{Product line (factor): `indoor` or `outdoor`.}
#'   \item{sales}{Monthly sales (units).}
#' }
#' @source Simulated; see `data-raw/generate_datasets.R`.
"monthly_sales"
