# Dataset documentation ------------------------------------------------------

#' Simulated lexical-decision experiment
#'
#' A reproducibly simulated psycholinguistic lexical-decision experiment, in
#' which participants judge whether letter strings are real words. The crossed
#' participant and item structure makes it a natural fit for mixed-effects
#' models, and hence for [optimizer_fixef_plot()], [coefficient_plot()] and the
#' distribution plots.
#'
#' The data are synthetic, generated by `data-raw/generate_datasets.R` with a
#' fixed seed; they do not describe any real individuals.
#'
#' @format A data frame with 960 rows and 7 variables:
#' \describe{
#'   \item{participant}{Participant identifier (factor, 24 levels).}
#'   \item{item}{Item identifier (factor, 40 levels).}
#'   \item{condition}{Priming condition: `related` or `unrelated`.}
#'   \item{modality}{Presentation modality: `visual` or `auditory`.}
#'   \item{word_frequency}{Word frequency on the Zipf scale.}
#'   \item{RT}{Reaction time, in milliseconds.}
#'   \item{accuracy}{Response accuracy: 1 correct, 0 incorrect.}
#' }
#' @source Simulated; see `data-raw/generate_datasets.R`.
"lexical_decision"

#' Simulated wellbeing survey
#'
#' A reproducibly simulated cross-sectional wellbeing survey with realistic
#' missing values (income is missing more often at higher stress). Used for the
#' descriptive, correlation and missing-data examples.
#'
#' The data are synthetic, generated by `data-raw/generate_datasets.R` with a
#' fixed seed; they do not describe any real individuals.
#'
#' @format A data frame with 300 rows and 9 variables:
#' \describe{
#'   \item{id}{Respondent identifier.}
#'   \item{region}{Region of residence: `North`, `South`, `East` or `West`.}
#'   \item{age}{Age in years.}
#'   \item{education}{Highest education level (ordered factor).}
#'   \item{income}{Annual income; contains missing values.}
#'   \item{stress}{Self-reported stress (1-7).}
#'   \item{sleep_hours}{Typical hours of sleep per night; contains missing values.}
#'   \item{exercise_days}{Days of exercise per week (0-7); contains missing values.}
#'   \item{life_satisfaction}{Life satisfaction (1-7); contains missing values.}
#' }
#' @source Simulated; see `data-raw/generate_datasets.R`.
"wellbeing_survey"

#' Simulated crop-yield field trial
#'
#' A reproducibly simulated agronomy field trial relating crop yield to
#' rainfall, fertiliser, soil pH and a management treatment. Used for the
#' regression, coefficient-plot and scatter-trend examples.
#'
#' The data are synthetic, generated by `data-raw/generate_datasets.R` with a
#' fixed seed.
#'
#' @format A data frame with 200 rows and 6 variables:
#' \describe{
#'   \item{field}{Field identifier.}
#'   \item{treatment}{Management treatment: `standard` or `enhanced`.}
#'   \item{rainfall}{Seasonal rainfall, in millimetres.}
#'   \item{fertilizer}{Fertiliser applied, in kilograms per hectare.}
#'   \item{soil_ph}{Soil pH.}
#'   \item{yield}{Crop yield, in tonnes per hectare.}
#' }
#' @source Simulated; see `data-raw/generate_datasets.R`.
"crop_yield"
